Updated heatmap visualizations
awslabs/sagemaker-debugger pull request #481
Opened 2021-04-08 03:40 UTC by NRauschmayr

### Description of changes:
I updated the heatmap to provide better visualizations for large scale distributed training jobs for instance users can now aggregate metrics per worker node.

#### Style and formatting:

I have run `pre-commit install` to ensure that auto-formatting happens with every commit.

#### Issue number, if available

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-13 02:22 UTC, NihalHarish requested changes
Can we add tests for this?

2021-04-13 19:30 UTC, NihalHarish commented
We need to add a way to test visualizations going forward; for now I will approve these changes.

2021-04-13 19:30 UTC, NihalHarish approved these changes

2021-04-16 16:53 UTC, merged

2022-04-08 00:11 UTC, atqy commented
Just want to ask, why is the `update_data` function deleted?