Support TF 2.5
awslabs/sagemaker-debugger pull request #505
Opened 2021-06-18 04:28 UTC by ndodda-amazon

### Description of changes:
Set the highest version that smdebug supports for TensorFlow to 2.5.

#### Style and formatting:

I have run `pre-commit install` to ensure that auto-formatting happens with every commit.

#### Issue number, if available

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-06-18 20:22 UTC, leleamol requested changes
Did we run the integration tests with TF 2.5?

2021-06-22 13:14 UTC, ndodda-amazon commented
> Did we run the integration tests with TF 2.5?

Set up a new build for TF 2.5, ran the integration tests and they passed. Here is the successful build: https://tiny.amazon.com/tsitmeze/CodeBuild-AWSDeve

2021-06-22 22:59 UTC, leleamol commented
> > Did we run the integration tests with TF 2.5?
> 
> Set up a new build for TF 2.5, ran the integration tests and they passed. Here is the successful build: https://tiny.amazon.com/tsitmeze/CodeBuild-AWSDeve

Thanks!

2021-06-22 23:00 UTC, leleamol approved these changes

2021-06-23 00:33 UTC, merged