Fix broken tests in test_keras_mirrored.py
awslabs/sagemaker-debugger pull request #526
Opened 2022-01-31 21:23 UTC by adimux

These tests were using `smdebug.tensorflow.get_hook()` to clean-up the Tensorflow hook and `get_hook()` is not functional anymore as it is part of the zero-code change feature which is deprecated/unmaintained.

In this particular test file, we are NOT testing zero-code change
therefore I'm just substituing the use of `get_hook()` by referencing the
manually created hook directly.

### Description of changes:

#### Style and formatting:

I have run `pre-commit install && pre-commit run --all-files` to ensure that auto-formatting happens with every commit.

#### Issue number, if available

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-01-31 21:27 UTC, ndodda-amazon requested changes
What framework version of TF is being used in the smdebug_tf2_build? Can you confirm that it's using TF 2.7?

2022-02-01 01:56 UTC, adimux commented
Our pipeline runs with an outdated version of Tensorflow (`2.4`). I will fix the pipeline later, but right now we need to unblock the release of `2.7`.
Fortunately, the DLC pipelines do run the sagemaker-debugger tests and I also ran them locally and they're green.

2022-02-01 02:15 UTC, hsl89 commented
LGTM

2022-02-01 02:29 UTC, Roshrini reviewed
Did you test it in TF2.7 DLC built through DLC pipeline?

2022-02-01 02:59 UTC, Roshrini approved these changes

2022-02-01 03:22 UTC, abhinavs95 commented
LGTM

2022-02-01 03:23 UTC, adimux commented
created other PR to be able to merge

2022-02-01 03:23 UTC, closed without merging

2022-02-01 17:53 UTC, olegtalalov commented on smdebug/core/utils.py
> +    raise Exception(f"No such framework type {framework_type}")
This should be ValueError exception.

2022-02-01 17:53 UTC, olegtalalov commented on tests/tensorflow/keras/test_keras.py
> +    if not is_framework_version_supported(FRAMEWORK.PYTORCH):
Why PYTORCH?